### ISSUE TITLE
assert(cyclic) fails

### ISSUE THREAD

**Issue by slinderman** [freedmand/combinational#1]
Cool project! I hit an assert when I ran it but otherwise really interesting.

Subset 1: PASSED
Subset 2: PASSED
Partial 1: PASSED
Partial 2: PASSED
Truth 1: PASSED
Truth 2: PASSED
Truth 3: PASSED
Truth 4: PASSED
Network 1: PASSED
Hi
0
Network 2: PASSED
Hi
Assertion failed: (cyclic), function RunTests, file combinational.c, line 808.
Abort trap: 6

**Comment by freedmand** [comment]
Thanks for the feedback! Resolved some code related to difficulties I had in detecting cycles, so all the tests should pass now. There may be a pending bug impacting overall evolution performance now as experiments set up identically to Kashtan and Alon's are not converging to perfect solutions; this may be related to cycles and that Kashtan and Alon's experiments do not actually work with proper circuit analysis. Will investigate further!

**Comment by freedmand** [comment]
The convergence bug has been resolved as well. See updated description. The evolution is now proceeding with performance comparable to that achieved by Kashtan and Alon. The program incorporates additional accurate information on its calculation of effective gates in the circuits and correctly tests for cyclic components within the directed graphs representing the circuits.
